[package]
name = "aoc"
version = "0.1.0"
authors = ["me"]
edition = "2018"

[dependencies]
maplit = "1.0.1"
file-reader = { path = "filereader" }
ferris-says = "0.2"
regex = "1"

[build-dependencies]
fs_extra = "1.2.0"
